spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storage
    username: root
    password: root

s3:
  client:
    enabled: true
    provider-name: minio/docbuddy
    url: http://minio:9000
    bucket: docbuddy
    access-key: minioadmin
    secret-key: minioadmin
    region: us-east-1